export const PLUGIN_NAME = "oh-my-openquant"
export const LEGACY_PLUGIN_NAME = "oh-my-openagent"
export const CONFIG_BASENAME = "oh-my-openquant"
export const LOG_FILENAME = "oh-my-openquant.log"
export const CACHE_DIR_NAME = "oh-my-openquant"
